version: "3.8"

services:

  database:
    build: 
      context: "${ENV_DATABASE_CONTEXT:-./database}"
    image: projetohospital-database
    environment:
      POSTGRES_PASSWORD: "${ENV_PG_PASS:-postgres}"
    volumes:
      - ${ENV_POSTGRESQL_DATA_DIR}:/var/lib/postgresql/data:z
    ports:
      - "5433:5432" 
    restart: always
  
  frontend:
  build:
      context: "${ENV_FRONTEND_CONTEXT:-./frontend}"
    image: projetohospital-frontend
    ports:
      - "8080:80"
    restart: always